
name: Intel Admin App Build using Node.JS with Gatsby

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the Code
        uses: actions/checkout@v3

      - name: Install Node.JS
        uses: actions/setup-node@v3.4.1
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Install Gatsby
        run: npm install -g gatsby-cli@4.20.0

      - name: Build the App
        run: gatsby build

      - name: Verify the Build is Successful or not
        run: ls -lrth public/

      - name: Create a Artifact from the Public Folder
        uses: actions/upload-artifact@v3
        with:
          name: public-folder
          path: public/

      # - name: Zip the Public Folder
      #   run: zip -r public.zip public/



  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [build]
    steps:

      - name: Download the artifact
        uses: actions/download-artifact@v3
        with:
          name: public-folder
          path: public/

      - name: Verify the PUblic folder and its contents
        run: |
          ls -l
          ls -l public/

      - name: Copy the Public Folder to Ubuntu
        uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: 'public/*'
          remote: 'public/'
          host: ${{secrets.HOST}}
          user: ${{secrets.USER}}
          password: ${{secrets.PASSWORD}}
          ssh_options: -o StrictHostKeyChecking=no
          pre_upload: rmdir /s /q public
          post_upload: echo "post upload"