
name: Intel Admin App Build using Node.JS with Gatsby

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the Code
        uses: actions/checkout@v3

      - name: Install Node.JS
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 14.20.0
          cache: 'npm'

      - name: Install Gatsby
        run: npm install --globally gatsby-cli

     
  
  deploy:
    name: Deployment
    
    runs-on: ubuntu-latest

    needs: [build]
    
    steps:
      - run: echo "Deploy is running"